#!/bin/bash
sandbox=$1
mcroot="${HOME}/.minecraft"

if [ -z "${sandbox}" ]; then
	echo "No input" >&2
	exit 1
fi

mkdir -p "${sandbox}/.minecraft" || exit 1
cd "${sandbox}/.minecraft"
mkdir bin
ln -sv "${mcroot}/bin/natives" bin/natives
cp -v "${mcroot}/bin"/*.jar bin
cp -v "${mcroot}/bin/version" "${mcroot}/bin/md5s" bin
cp -rv "${mcroot}/config" config
ln -sv "${mcroot}/crash-reports" "${mcroot}/lastlogin" "${mcroot}/launcher.jar" "${mcroot}"/options* "${mcroot}/saves" "${mcroot}/screenshots" .

exit 0
